name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  file_picker: ^8.1.5
  http: ^1.3.0
  flutter_image_compress: ^2.3.0
  image: ^4.4.0
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
